import {
  User,
  Member,
  Trainer,
  MembershipPlan,
  GymClass,
  Reward,
  Attendance,
  WorkoutLog,
  BodyMeasurement,
  Payment,
  Notification,
} from "../types";

export const MOCK_USERS: Record<string, User> = {
  admin: {
    id: "user-admin",
    email: "superadmin@apexfitness.com",
    role: "super_admin",
    firstName: "Alexander",
    lastName: "Vance",
    phone: "+1 (555) 901-1122",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
  },
  staff: {
    id: "user-staff",
    email: "staff@apexfitness.com",
    role: "admin",
    firstName: "Rachel",
    lastName: "Greene",
    phone: "+1 (555) 901-3344",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150",
  },
  trainer: {
    id: "user-trainer",
    email: "marcus@apexfitness.com",
    role: "trainer",
    firstName: "Marcus",
    lastName: "Steele",
    phone: "+1 (555) 234-5678",
    status: "active",
    avatarUrl: "https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=150",
  },
  member: {
    id: "user-member",
    email: "sarah@example.com",
    role: "member",
    firstName: "Sarah",
    lastName: "Connor",
    phone: "+1 (555) 789-0001",
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
};

export const MOCK_PLANS: MembershipPlan[] = [
  {
    id: "plan-trial",
    name: "Day Pass / Trial",
    code: "PLAN-DAY",
    description: "Single-day access to gym facilities, lockers, and dry sauna.",
    durationDays: 1,
    price: 20.0,
    planType: "trial",
    benefits: JSON.stringify(["Full floor access for 24 hours", "Standard locker access", "Free hydration bar"]),
    maxClassesPerWeek: 0,
    hasTrainerAccess: false,
    isActive: true,
  },
  {
    id: "plan-monthly",
    name: "Monthly Athlete Pass",
    code: "PLAN-MONTHLY",
    description: "Flexible monthly training membership with unrestricted access to all strength & cardio areas.",
    durationDays: 30,
    price: 59.99,
    planType: "standard",
    benefits: JSON.stringify(["Unlimited gym floor access", "Locker room & Finnish sauna", "Free mobile app QR check-in", "1 Group class per week"]),
    maxClassesPerWeek: 1,
    hasTrainerAccess: false,
    isActive: true,
  },
  {
    id: "plan-quarterly",
    name: "Quarterly Pro Conditioning",
    code: "PLAN-QUARTERLY",
    description: "Comprehensive 90-day athletic program with included fitness classes and recovery lounge access.",
    durationDays: 90,
    price: 159.99,
    planType: "premium",
    benefits: JSON.stringify(["Unlimited gym access", "Unlimited group classes", "1 Complimentary 1-on-1 PT Session", "Recovery lounge & massage chairs", "2 Guest passes per month"]),
    maxClassesPerWeek: 5,
    hasTrainerAccess: true,
    isActive: true,
  },
  {
    id: "plan-annual",
    name: "Annual All-Access Championship",
    code: "PLAN-ANNUAL",
    description: "The pinnacle 365-day membership. VIP keyless entry, recovery suite, and monthly trainer consultations.",
    durationDays: 365,
    price: 499.99,
    planType: "premium",
    benefits: JSON.stringify(["24/7 VIP keyless QR entry", "Unlimited classes & recovery zone", "Monthly 1-on-1 PT consultation", "10% discount on gym apparel and gear", "Unlimited guest access"]),
    maxClassesPerWeek: 10,
    hasTrainerAccess: true,
    isActive: true,
  },
  {
    id: "plan-student",
    name: "Student Performance Pass",
    code: "PLAN-STUDENT",
    description: "Budget-friendly membership for high school and university students with valid student ID.",
    durationDays: 30,
    price: 39.99,
    planType: "student",
    benefits: JSON.stringify(["Full strength & cardio access", "Study lounge Wi-Fi", "Locker room & showers", "Off-peak and weekend access"]),
    maxClassesPerWeek: 0,
    hasTrainerAccess: false,
    isActive: true,
  },
];

export const MOCK_TRAINERS: Trainer[] = [
  {
    id: "trainer-1",
    userId: "user-trainer",
    specialization: "Hypertrophy & Heavy Powerlifting",
    bio: "Former collegiate strength coach with 8+ years experience coaching national powerlifting medalists.",
    experienceYears: 8,
    hourlyRate: 75.0,
    rating: 4.95,
    maxClients: 25,
    user: MOCK_USERS.trainer,
  },
  {
    id: "trainer-2",
    userId: "user-trainer-2",
    specialization: "HIIT Conditioning & Olympic Weightlifting",
    bio: "CrossFit Level 3 certified coach specializing in functional conditioning and body recomposition.",
    experienceYears: 6,
    hourlyRate: 65.0,
    rating: 4.88,
    maxClients: 20,
    user: {
      id: "user-trainer-2",
      email: "elena@apexfitness.com",
      role: "trainer",
      firstName: "Elena",
      lastName: "Rostova",
      status: "active",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    },
  },
  {
    id: "trainer-3",
    userId: "user-trainer-3",
    specialization: "Functional Mobility & Athletic Recovery",
    bio: "Doctor of Physical Therapy candidate focusing on posture correction, joint decompression, and athletic longevity.",
    experienceYears: 5,
    hourlyRate: 70.0,
    rating: 4.92,
    maxClients: 18,
    user: {
      id: "user-trainer-3",
      email: "david@apexfitness.com",
      role: "trainer",
      firstName: "David",
      lastName: "Chen",
      status: "active",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    },
  },
];

export const MOCK_MEMBERS: Member[] = [
  {
    id: "mem-1",
    userId: "user-member",
    memberCode: "MEM-10001",
    qrCodeToken: "APEX-MEM-10001-TOKEN-8A9B",
    fitnessGoals: "Hypertrophy and Core Strength for Endurance",
    rewardCoins: 450,
    user: MOCK_USERS.member,
    memberships: [
      {
        id: "m-sub-1",
        memberId: "mem-1",
        planId: "plan-quarterly",
        startDate: "2026-09-01T00:00:00Z",
        endDate: "2026-11-30T00:00:00Z",
        status: "active",
        autoRenew: true,
        plan: MOCK_PLANS[2],
      },
    ],
    aiActivityScores: [
      {
        id: "score-1",
        score: 88,
        attendanceScore: 92,
        workoutScore: 85,
        consistencyScore: 90,
        riskLevel: "low",
        insights: "High performance athlete! Consistency has improved 15% over the past 30 days.",
      },
    ],
  },
  {
    id: "mem-2",
    userId: "user-mem-2",
    memberCode: "MEM-10002",
    qrCodeToken: "APEX-MEM-10002-TOKEN-3C4D",
    fitnessGoals: "Fat Loss and Athletic Cardiovascular Conditioning",
    rewardCoins: 220,
    user: {
      id: "user-mem-2",
      email: "alex@example.com",
      role: "member",
      firstName: "Alex",
      lastName: "Mercer",
      phone: "+1 (555) 789-0002",
      status: "active",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    },
    memberships: [
      {
        id: "m-sub-2",
        memberId: "mem-2",
        planId: "plan-monthly",
        startDate: "2026-09-15T00:00:00Z",
        endDate: "2026-10-15T00:00:00Z",
        status: "active",
        autoRenew: false,
        plan: MOCK_PLANS[1],
      },
    ],
    aiActivityScores: [
      {
        id: "score-2",
        score: 72,
        attendanceScore: 75,
        workoutScore: 70,
        consistencyScore: 70,
        riskLevel: "moderate",
        insights: "Engagement stable. Recommend introducing group class challenge to increase weekly visits.",
      },
    ],
  },
  {
    id: "mem-3",
    userId: "user-mem-3",
    memberCode: "MEM-10003",
    qrCodeToken: "APEX-MEM-10003-TOKEN-5E6F",
    fitnessGoals: "Powerlifting PRs (Squat, Bench, Deadlift)",
    rewardCoins: 680,
    user: {
      id: "user-mem-3",
      email: "jordan@example.com",
      role: "member",
      firstName: "Jordan",
      lastName: "Lee",
      phone: "+1 (555) 789-0003",
      status: "active",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
    },
    memberships: [
      {
        id: "m-sub-3",
        memberId: "mem-3",
        planId: "plan-annual",
        startDate: "2026-01-10T00:00:00Z",
        endDate: "2027-01-10T00:00:00Z",
        status: "active",
        autoRenew: true,
        plan: MOCK_PLANS[3],
      },
    ],
    aiActivityScores: [
      {
        id: "score-3",
        score: 95,
        attendanceScore: 98,
        workoutScore: 95,
        consistencyScore: 92,
        riskLevel: "low",
        insights: "Elite gym dedication. Set 2 personal records this month.",
      },
    ],
  },
  {
    id: "mem-4",
    userId: "user-mem-4",
    memberCode: "MEM-10004",
    qrCodeToken: "APEX-MEM-10004-TOKEN-7G8H",
    fitnessGoals: "General Health and Posture Improvement",
    rewardCoins: 50,
    user: {
      id: "user-mem-4",
      email: "chloe@example.com",
      role: "member",
      firstName: "Chloe",
      lastName: "Bennett",
      phone: "+1 (555) 789-0004",
      status: "active",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
    },
    memberships: [
      {
        id: "m-sub-4",
        memberId: "mem-4",
        planId: "plan-monthly",
        startDate: "2026-08-01T00:00:00Z",
        endDate: "2026-09-01T00:00:00Z",
        status: "expired",
        autoRenew: false,
        plan: MOCK_PLANS[1],
      },
    ],
    aiActivityScores: [
      {
        id: "score-4",
        score: 28,
        attendanceScore: 20,
        workoutScore: 30,
        consistencyScore: 35,
        riskLevel: "high",
        insights: "Member has not visited in over 20 days and membership has expired. Staff outreach advised.",
      },
    ],
  },
];

export const MOCK_CLASSES: GymClass[] = [
  {
    id: "class-1",
    name: "Olympic Barbell & Power Clinic",
    description: "Technical coaching on snatch, clean & jerk, and posterior chain explosive power.",
    category: "strength",
    trainerId: "trainer-1",
    room: "Barbell Arena",
    maxCapacity: 12,
    startTime: "09:00",
    endTime: "10:15",
    scheduleDate: "2026-10-05T09:00:00Z",
    durationMinutes: 75,
    trainer: MOCK_TRAINERS[0],
    bookings: [
      { id: "cb-1", classId: "class-1", memberId: "mem-1", status: "booked", bookedAt: "2026-10-01" },
      { id: "cb-2", classId: "class-1", memberId: "mem-3", status: "booked", bookedAt: "2026-10-02" },
    ],
  },
  {
    id: "class-2",
    name: "Tactical Metabolic HIIT",
    description: "High-octane interval conditioning featuring kettlebells, assault bikes, and rowing sprints.",
    category: "hiit",
    trainerId: "trainer-2",
    room: "Studio B",
    maxCapacity: 16,
    startTime: "18:00",
    endTime: "19:00",
    scheduleDate: "2026-10-05T18:00:00Z",
    durationMinutes: 60,
    trainer: MOCK_TRAINERS[1],
    bookings: [
      { id: "cb-3", classId: "class-2", memberId: "mem-2", status: "booked", bookedAt: "2026-10-01" },
    ],
  },
  {
    id: "class-3",
    name: "Athletic Mobility & Hip Decompression",
    description: "Deep tissue myofascial release, joint decompression, and mobility drills for lifters.",
    category: "yoga",
    trainerId: "trainer-3",
    room: "Zen Studio",
    maxCapacity: 20,
    startTime: "19:30",
    endTime: "20:30",
    scheduleDate: "2026-10-06T19:30:00Z",
    durationMinutes: 60,
    trainer: MOCK_TRAINERS[2],
    bookings: [],
  },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: "rew-1",
    title: "Apex Stealth Shaker Bottle (800ml)",
    description: "BPA-free matte black stainless steel shaker with surgical grade mixing whisk.",
    pointsCost: 150,
    category: "merchandise",
    stockQuantity: 45,
    isActive: true,
  },
  {
    id: "rew-2",
    title: "Heavy Duty Lifting Wrist Straps",
    description: "Reinforced cotton padded straps engineered for maximal pulling grip on heavy lifts.",
    pointsCost: 200,
    category: "merchandise",
    stockQuantity: 30,
    isActive: true,
  },
  {
    id: "rew-3",
    title: "1-on-1 Personal Training Session Voucher",
    description: "60-minute private personal coaching session with any senior trainer of your choice.",
    pointsCost: 500,
    category: "free_session",
    stockQuantity: 20,
    isActive: true,
  },
  {
    id: "rew-4",
    title: "20% Off Next Membership Renewal",
    description: "Apply an instant 20% discount coupon towards any upcoming membership term.",
    pointsCost: 350,
    category: "discount",
    stockQuantity: 100,
    isActive: true,
  },
  {
    id: "rew-5",
    title: "Apex Elite Performance Zip Hoodie",
    description: "Athletic taper breathable fleece hoodie with laser-cut ventilation and embroidered logo.",
    pointsCost: 800,
    category: "merchandise",
    stockQuantity: 15,
    isActive: true,
  },
];

export const MOCK_ATTENDANCES: Attendance[] = [
  {
    id: "att-1",
    memberId: "mem-1",
    checkInTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    checkOutTime: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    checkInMethod: "qr",
    notes: "Session duration: 60 mins",
    member: MOCK_MEMBERS[0],
  },
  {
    id: "att-2",
    memberId: "mem-3",
    checkInTime: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    checkOutTime: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
    checkInMethod: "qr",
    notes: "Session duration: 90 mins",
    member: MOCK_MEMBERS[2],
  },
  {
    id: "att-3",
    memberId: "mem-2",
    checkInTime: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    checkOutTime: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    checkInMethod: "kiosk",
    notes: "Session duration: 60 mins",
    member: MOCK_MEMBERS[1],
  },
];

export const MOCK_WORKOUT_LOGS: WorkoutLog[] = [
  {
    id: "wlog-1",
    memberId: "mem-1",
    workoutName: "Heavy Push & Shoulder Hypertrophy",
    date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    durationMinutes: 65,
    caloriesBurned: 480,
    rating: 5,
    overallNotes: "Hit strong depth on incline dumbbell presses. Shoulder pump felt fantastic.",
    entries: [
      { id: "e1", exerciseName: "Barbell Bench Press", muscleGroup: "Chest", setNumber: 1, repsCompleted: 8, weightKg: 85, isPersonalRecord: true },
      { id: "e2", exerciseName: "Incline Dumbbell Press", muscleGroup: "Chest", setNumber: 2, repsCompleted: 10, weightKg: 32, isPersonalRecord: false },
      { id: "e3", exerciseName: "Standing Overhead Press", muscleGroup: "Shoulders", setNumber: 3, repsCompleted: 6, weightKg: 55, isPersonalRecord: true },
      { id: "e4", exerciseName: "Cable Lateral Raises", muscleGroup: "Shoulders", setNumber: 4, repsCompleted: 15, weightKg: 14, isPersonalRecord: false },
    ],
  },
];

export const MOCK_MEASUREMENTS: BodyMeasurement[] = [
  {
    id: "bm-1",
    memberId: "mem-1",
    recordedDate: "2026-08-01T00:00:00Z",
    weightKg: 78.5,
    heightCm: 175.0,
    bmi: 25.63,
    bodyFatPercentage: 21.0,
    muscleMassKg: 58.2,
    chestCm: 101.0,
    waistCm: 84.0,
    armCm: 36.5,
    notes: "Initial enrollment baseline",
  },
  {
    id: "bm-2",
    memberId: "mem-1",
    recordedDate: "2026-10-01T00:00:00Z",
    weightKg: 74.2,
    heightCm: 175.0,
    bmi: 24.23,
    bodyFatPercentage: 17.5,
    muscleMassKg: 60.1,
    chestCm: 103.5,
    waistCm: 79.5,
    armCm: 38.0,
    notes: "Noticeable reduction in waistline, increased bicep/tricep cross-section.",
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    transactionId: "TXN-2026-M10001",
    invoiceNumber: "INV-2026-0081",
    memberId: "mem-1",
    amount: 159.99,
    netAmount: 159.99,
    currency: "USD",
    paymentMethod: "credit_card",
    paymentStatus: "completed",
    paymentType: "membership",
    createdAt: "2026-09-01T12:00:00Z",
    notes: "Quarterly Pro Conditioning enrollment",
    member: MOCK_MEMBERS[0],
  },
  {
    id: "pay-2",
    transactionId: "TXN-2026-M10002",
    invoiceNumber: "INV-2026-0082",
    memberId: "mem-2",
    amount: 59.99,
    netAmount: 59.99,
    currency: "USD",
    paymentMethod: "online",
    paymentStatus: "completed",
    paymentType: "membership",
    createdAt: "2026-09-15T10:30:00Z",
    notes: "Monthly Athlete Pass",
    member: MOCK_MEMBERS[1],
  },
  {
    id: "pay-3",
    transactionId: "TXN-2026-M10003",
    invoiceNumber: "INV-2026-0083",
    memberId: "mem-3",
    amount: 499.99,
    netAmount: 499.99,
    currency: "USD",
    paymentMethod: "bank_transfer",
    paymentStatus: "completed",
    paymentType: "membership",
    createdAt: "2026-01-10T14:15:00Z",
    notes: "Annual All-Access Championship VIP",
    member: MOCK_MEMBERS[2],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-member",
    title: "Personal Record Achieved! 🔥",
    message: "You smashed your Barbell Bench Press PR with 85.0 kg! +25 bonus reward coins awarded.",
    type: "workout",
    isRead: false,
    createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-member",
    title: "Class Reminder: Olympic Barbell Clinic",
    message: "Your upcoming class starts tomorrow at 09:00 in Barbell Arena. Bring your lifting straps!",
    type: "booking",
    isRead: false,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-member",
    title: "Membership Status: Active",
    message: "Your Quarterly Pro Conditioning plan has 58 days remaining. Auto-renewal is enabled.",
    type: "membership",
    isRead: true,
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
];
